<a href="https://colab.research.google.com/github/imtiazdeepto/R-Language/blob/main/3_R_Basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
df<-data.frame(
student_id = c(101,102,103,104,105,106,107,108),
math = c(75,88,92,67,81,95,78,84),
programming = c(80,90,89,70,75,98,82,88)
)
df

  student_id math programming
1 101        75   80
2 102        88   90
3 103        92   89
4 104        67   70
5 105        81   75
6 106        95   98
7 107        78   82
8 108        84   88

In [25]:
#Calculate the average marks for each subject.
math_avg<-mean(math)
math_avg
prog_avg<-mean(programming)
prog_avg

[1] 82.5

[1] 84

In [26]:
# Find students scoring above the class average in Programming.
df[df$programming>prog_avg,]

  student_id math programming
2 102        88   90
3 103        92   89
6 106        95   98
8 108        84   88

In [30]:
# Calculate the total marks of each student.
df$total<-math+programming
df

  student_id math programming total
1 101        75   80          155
2 102        88   90          178
3 103        92   89          181
4 104        67   70          137
5 105        81   75          156
6 106        95   98          193
7 107        78   82          160
8 108        84   88          172

In [41]:
df$grade<-ifelse(df$total>=180,'A',ifelse((df$total>=160),"B",'C'))
df

  student_id math programming total grade
1 101        75   80          155   C
2 102        88   90          178   B
3 103        92   89          181   A
4 104        67   70          137   C
5 105        81   75          156   C
6 106        95   98          193   A
7 107        78   82          160   B
8 108        84   88          172   B

In [44]:
table(df$grade)

A B C
2 3 3