<a href="https://colab.research.google.com/github/imtiazdeepto/R-Language/blob/main/4_R_Basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [51]:
df <- data.frame(
ID = c(101,102,103,104,105,106,107,108),
Age = c(20,21,22,20,23,21,22,20),
Department = c("CSE","CSE","EEE","CSE","EEE","CSE","BBA","BBA"),
Math = c(75,88,92,67,81,95,78,84),
Programming = c(80,90,89,70,75,98,82,88)
)

In [52]:
df

  ID  Age Department Math Programming
1 101 20  CSE        75   80
2 102 21  CSE        88   90
3 103 22  EEE        92   89
4 104 20  CSE        67   70
5 105 23  EEE        81   75
6 106 21  CSE        95   98
7 107 22  BBA        78   82
8 108 20  BBA        84   88

In [54]:
df$total<-math + programming
df

  ID  Age Department Math Programming total
1 101 20  CSE        75   80          155
2 102 21  CSE        88   90          178
3 103 22  EEE        92   89          181
4 104 20  CSE        67   70          137
5 105 23  EEE        81   75          156
6 106 21  CSE        95   98          193
7 107 22  BBA        78   82          160
8 108 20  BBA        84   88          172

In [67]:
df[which(df$Department=='CSE' & df$avg>85),]

  ID  Age Department Math Programming total avg
2 102 21  CSE        88   90          178   89.0
6 106 21  CSE        95   98          193   96.5

In [57]:
df$avg<-df$total/2
df

  ID  Age Department Math Programming total avg
1 101 20  CSE        75   80          155   77.5
2 102 21  CSE        88   90          178   89.0
3 103 22  EEE        92   89          181   90.5
4 104 20  CSE        67   70          137   68.5
5 105 23  EEE        81   75          156   78.0
6 106 21  CSE        95   98          193   96.5
7 107 22  BBA        78   82          160   80.0
8 108 20  BBA        84   88          172   86.0

In [65]:
df[df$avg>85 & df$Department=='CSE',]

  ID  Age Department Math Programming total avg
2 102 21  CSE        88   90          178   89.0
6 106 21  CSE        95   98          193   96.5

In [71]:
aggregate(Age~Department,data=df,mean)

  Department Age
1 BBA        21.0
2 CSE        20.5
3 EEE        22.5

In [73]:
aggregate(total~Department,data=df,mean)

  Department total
1 BBA        166.00
2 CSE        165.75
3 EEE        168.50

In [77]:
sorted <- df[
  order(df$total),
]
sorted

  ID  Age Department Math Programming total avg
4 104 20  CSE        67   70          137   68.5
1 101 20  CSE        75   80          155   77.5
5 105 23  EEE        81   75          156   78.0
7 107 22  BBA        78   82          160   80.0
8 108 20  BBA        84   88          172   86.0
2 102 21  CSE        88   90          178   89.0
3 103 22  EEE        92   89          181   90.5
6 106 21  CSE        95   98          193   96.5